server:
  port: 8082

spring:
  application:
    name: storage-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://[your db]:3306/common?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: common
    password: 4ccymwAhc5Y7GsPN
  cloud:
    nacos:
      discovery:
        server-addr: [your db]:8848

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.common.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: demo-tx-group
  service:
    vgroup-mapping:
      demo-tx-group: default
    grouplist:
      default: 127.0.0.1:8091
  registry:
    type: file
  config:
    type: file

logging:
  level:
    io.seata: info
    com.example: debug 