server:
  port: 8080

spring:
  application:
    name: mcp-demo
  datasource:
    url: jdbc:mysql://[your db]:3306/common?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: common
    password: 4ccymwAhc5Y7GsPN
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
      
logging:
  level:
    root: info
    com.example.mcpdemo: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mcp-demo.log
    
# MCP 自定义配置  
mcp:
  server:
    # MCP服务端点
    endpoint: /mcp
    # 默认模型
    default-model: gpt-3.5-turbo
    # 支持的模型
    models:
      - gpt-3.5-turbo
      - gpt-4
      - qwen-turbo
      - qwen-plus
      - glm-4
    # 会话超时时间（毫秒）
    session-timeout: 1800000 
    # 最大上下文长度
    max-context-size: 1000
    # 最大会话数
    max-sessions: 100 